### PR TITLE
DSEGOG-7 user can resize columns

### PR DESCRIPTION
**Pull request by sam-glendenning**
## Description
Adding functionality to allow the user to resize the table columns by dragging the dividers placed between column headers. This uses React Table's useResizeColumns plugin to natively handle table resizing and management of column state.

The functionality works reasonably well but may need to be expanded upon later. One notable bug that exists at the moment is that, when the columns are reordered, added to or removed from, the sizes go back to the default width. We'll need to fix this later on. However, for the meantime, this might satisfy the requirement.

This PR also includes the config file defining the types necessary to extend the functionality of React Table to include all of its plugins. Tanstack do not maintain these types, hence we define them ourselves. See here for more info - https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table

## Testing instructions
Experiment with resizing columns as well as adding and removing columns to see how the functionality works together.

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage

## Agile board tracking
Closes [DSEGOG-7](https://stfc.atlassian.net/jira/software/projects/DSEGOG/boards/22?selectedIssue=DSEGOG-7)

### CODE REVIEW

**Review by louise-davies — COMMENTED** [review]
Code looks good - after we spoke though I fiddled with some stuff and I think I've improved the behaviour slightly? In that the column dividers no longer get out of line. See gifs below:

current behaviour:

OG-resize-old

proposed behaviour:

OG-resize-new

Thoughts @sam-glendenning ? If you agree that you think this is good I can commit what I have

**Comment by sam-glendenning** [comment]
@louise-davies I noticed that too, it was bugging me - please commit! I'd love to see the solution

**Comment by louise-davies** [comment]
@sam-glendenning if you're happy with my code I'll approve the PR so it can be merged

**Comment by sam-glendenning** [comment]
@louise-davies sorry, got distracted. Go for it and thanks for the help!

**Review by louise-davies — APPROVED** [review]

**Pull request merged**
