### PR TITLE
DSEGOG-103 make search box collapsible

### PR DESCRIPTION
**Pull request by louise-davies**
## Description
Add a button to expand/collapse the search box

There's no wireframe/mockup showing the expand/collapse functionality, so I've just put it with the other buttons (e.g. `Filters` etc.) but this can easily be moved

## Testing instructions
Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage

## Agile board tracking
Closes DSEGOG-103

### CODE REVIEW

**Review by sam-glendenning — APPROVED** [review]
Works well! I wonder, what's your thoughts on having a little chip to the right of the words 'Hide/Show Search' that contains a number equalling the number of active search parameters? For example, if we have a shot number range selected, the chip contains 1. If we have a shot number and date range selected, the chip contains 2. If none are selected, there is no chip.

The purpose is purely to highlight that there are search parameters currently active when the user has the search collapsed and may have forgotten these are active

**Comment by louise-davies** [comment]
@sam-glendenning sounds like a neat idea but I'm not sure how it would work with the idea of correlated fields - e.g. searching by experiment id will automatically adjust the date range to the date range of the experiment - does that mean the user has filtered by date range or not? I'd stick with what we have for now, and either @mattjSTFC or users can suggest improvements

**Comment by sam-glendenning** [comment]
Yes I had similar concerns with the timeframe adjustment. I'll approve what's here since it's good as is

**Comment by sam-glendenning** [comment]
Actually, I've already approved. Merge when ready!

**Pull request merged**
